version: '3.7'

services:
  precipitate-postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=precipitation_dev
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data:
    